# configs/field_definitions/ju_fields.yaml

doc_type: "주민등록등본 (JU)"
template_folder: "JU" # assets/templates/ 하위 폴더 이름

# 필드 이름 목록
fields:
  - ISSUER_TOP
  - ISSUER_BOTTOM
  - APPLICANT
  - APPLICANT_BIRTH
  - MAIN_NAME
  - MAIN_NAME_CN
  - MAIN_ADDRESS
  - MAIN_EVENT_DATE
  - MAIN_REPORT_DATE
  - MEMBER1_NUMBER
  - MEMBER1_RELATION
  - MEMBER1_NAME
  - MEMBER1_JUMIN
  - MEMBER1_NAME_CN
  - MEMBER1_EVENT_DATE
  - MEMBER1_REPORT_DATE
  - MEMBER1_STATUS
  - MEMBER1_CHANGE_REASON
  - MEMBER2_NUMBER
  - MEMBER2_RELATION
  - MEMBER2_NAME
  - MEMBER2_JUMIN
  - MEMBER2_NAME_CN
  - MEMBER2_EVENT_DATE
  - MEMBER2_REPORT_DATE
  - MEMBER2_STATUS
  - MEMBER2_CHANGE_REASON
  - MEMBER3_NUMBER
  - MEMBER3_RELATION
  - MEMBER3_NAME
  - MEMBER3_JUMIN
  - MEMBER3_NAME_CN
  - MEMBER3_EVENT_DATE
  - MEMBER3_REPORT_DATE
  - MEMBER3_STATUS
  - MEMBER3_CHANGE_REASON
  - MEMBER4_NUMBER
  - MEMBER4_RELATION
  - MEMBER4_NAME
  - MEMBER4_JUMIN
  - MEMBER4_NAME_CN
  - MEMBER4_EVENT_DATE
  - MEMBER4_REPORT_DATE
  - MEMBER4_STATUS
  - MEMBER4_CHANGE_REASON
  - MEMBER5_NUMBER
  - MEMBER5_RELATION
  - MEMBER5_NAME
  - MEMBER5_JUMIN
  - MEMBER5_NAME_CN
  - MEMBER5_EVENT_DATE
  - MEMBER5_REPORT_DATE
  - MEMBER5_STATUS
  - MEMBER5_CHANGE_REASON
